// Generated by npm run protocol:generate.
export const GENERATED_PROTOCOL = {
  "protocolVersion": "ACQUAINTANCE/1.0",
  "cypherPhrase": "PRIVACY IS THE POWER TO REVEAL YOURSELF SELECTIVELY",
  "cypherTokens": [
    "YOURSELF",
    "PRIVACY",
    "POWER",
    "IS",
    "SELECTIVELY",
    "TO",
    "THE",
    "REVEAL"
  ],
  "proofCapsuleKey": "POLICY 1049 / MINIMAL DISCLOSURE VERIFIED",
  "builder": {
    "answer": "PRIVATE AGENT / EPHEMERAL MEMORY / USER-HELD KEY",
    "options": [
      "CLOUD AGENT / PERMANENT MEMORY / PLATFORM KEY",
      "PRIVATE AGENT / EPHEMERAL MEMORY / USER-HELD KEY",
      "SOCIAL AGENT / PUBLIC MEMORY / SHARED KEY"
    ],
    "sibling": "358fbb21b0e53c256e26402d32f9f8fa569c22526a633d3d261303809644e564",
    "root": "5b18843f0da98f11980e860ec073998d757e77da36a2ec64b369acffb5c52663"
  },
  "capsules": {
    "cypherpunk": {
      "salt": "6ogpI2b8APLTMPiR/WnDMA==",
      "iterations": 120000,
      "iv": "KQF+wSCI/mQm4NxI",
      "ciphertext": "dTfmnENBkkyQKA6nD6rPfruTmTkcm/VIpfMkgP35wknAdN9NuXfqAq918TJ5RdxUZx9bD0S53W10ngZyOJdlgJkDkqFpO1mgDeDGWjdCy3PROOhfpB4zc3a3otzx7QdycekwHWe2m4BQIt3o8pa+YQ6E3TXczDSShbjvAnFilM6SAeYnQdyTVZXRN7G6LhSCOFvq0ra79BrHP+4vTiK0+SWYmU4ZbzBoBEGhbCdTi7kQH7VLNN+RUjIndzXiyT21dCro6kJuDgWFWJUYk2HC2PU8X1SoQDo7Q3/wE2UNqvjZwxovv7b72WoQ6W7aO/nwueYZ3ndrw6XRJFgFFy46hWaE4YKMejYC8eNX3ZzjSBt8bk9Fmu7++nUUAtf/Q1xeQKGa/ONgUnEglboSKs8rLWmBrQMibaIQji0xZw==",
      "tag": "UaLFgNTHueubJGJMbcBISw=="
    },
    "proof": {
      "salt": "dcEKSMxyVENbEThZiq277w==",
      "iterations": 120000,
      "iv": "mkUucw8WEf874x2d",
      "ciphertext": "EXEuHLVuLyoTk/q2B4p9Pg1CjJ+xvB6wj7udY53vDqxhis7Gj1emQBoFF7WHNCyG2QBwKtjoyr697SkX/+oGdsGaql2RoKilLBCnavtanwY0u4PDMecnNQhYDDW24iUX0D0jKPGfWvIqoXvdbdAAvVKFIBah4MzHigy7vtLOXi7kiW1Tp91gdK2MWFLjRaKuFpfIqRPiJpi7DCMxhUlAww/wR1/s5GZFWXc8cfomlsw26oHmjnpuQ0baZsjAT05PLQGCok5fXFVjeaiL+cAD+/TjfphetudXHI9J9VHtNxaRLhOC57Jy2d73q71klMmaJHGfrUsaPID7ym6qZ6HRfHHYH5K3LBZn2X9/LVoRW+JTdPu/NVf0Xo9Qh2RVx3wmBfWpnGs6D2B/gmFGTeJBtEAZgaly8sTpVXtMApytwa/n/8zmQfjKhwYy3uL/qoSQxR3LXw0D+xir",
      "tag": "pQ+LLKNEtdL9Y1r3cKxEeg=="
    },
    "builder": {
      "salt": "q7MpG0bykT2YkK7IY9wbIA==",
      "iterations": 120000,
      "iv": "v7cPQ+TNzlyYdt/+",
      "ciphertext": "T/eWRKnNw30STvHGQ3WjeOQeCXiixD9/vq0/hMF+IawlTWq3H1cZQYiHxVkLZLu6yQsWekFEPPer42wXh4HByRFMWMTKKOi8+P8cNt+IhqhAMmyEFUsm01beJG6HAZ7JbDERULUgSKgQqDzMcjexTsas9Gh9CAyPDvhpMnxMPv7bGJ5Q9dxSkQle1vjRvgMEuxIqOmciwtreroOlQ8ny4rs+8cvHJS03IqcycayQZRGCAAQVx8jzEW5NwFymYzXrEXdbUt1Uj/ufNsW4qjWNWBLwVn+JLrIKWTAI1RnU6fTv+D+hX1QRWxbtPX7XhPX6GjqeL23NdOF75Le5qttwxkmu+2rccpUiFZuUL7JZXkGIZLW6PMg5oZL9Goi9dPm2TBW4uZowQpFylzu3xXY55UXzPOHfJTlMzaBEKuDx90sTW77U7nHmLwneWEbZVARtkDhWJQcqkMcyqRLfjwUiNZ9jVnC7YpIeNh2/8GzG8aCgGJKS5FI5J06kO36A2g==",
      "tag": "oxxDZsPMyafWM7DbhYkbbg=="
    },
    "final": {
      "iv": "tUbr388abvj7XFA7",
      "ciphertext": "2p8+DFb2h/dEWuHtwNP2AQq6apPo0SZKQq5YJTRT+V6ZDlVHhQnsyqLDUy4KMlwzHcLXzlmCFrmkwVNW7hIrSwqXaozShtawW0bZ7QhjbNppt3GR5Z86dG18m6gylPayjuTEKUHHK2JFv6nePRvaHtbyLLyNXWoLeFB74vyQHIUT/ldUE5f5nukMBFm6RADWoV1Z7RIwgHFUwRKrTyXtTI0qxpvJBYhdpb8rbh+NYZJ3AAZbtIvRSV7JwyJ74aO2xooC5MbPlxnX9V5ScRoA2dCX2o5OuqWGHZI2zv1N3h/7+xoo6l3ErieDViP4NC6VjvqrahcW8G0MyCKYU8rdL3kdwFZ9JuCxfOvF0DBIawwWd9HJEPjaQWQPlyOSALdGTZC1Xy5roZoQBuyvtbGhl3RKZkYQ4SH9g2M1Lss+IDd7WnepD0imfcvlzgg8gPRZYACWp1/pox9D1nyUXOgXlC0tRlI0VWkSy+SJ/QWjp03PoZhpGS8tE7Dmy1c+pgOmAlKe6AAowPP2cKtderNhp5l5tMnJj2ttK63uMgZ6v49pRMU5SLaQHopqD+tYQ4F/lFZ9MJdvdLlRf6GP50elQIvLeSnDy/DXE/MwXLioSemyVeCBIkqAlFCy/uyVDWbl1qvSJgDECZQLVAohhgujehNofzf4sWqy1a4LMDL2de/a7vUyCNdC7FPYWWH+yLqIyW6T3B42a6WiAZZZ486WtmRnzaJxg+J5TFca1PdNyVhxxwcUPvs4exSaB9HUf+h/DBzgVIOF20Ggx2Cp4HQKB8oUui1UjHZ/pcZ7HBV8CaP23SSdlm94Zd7pv0/bEbxWn9civwguZzs8OQ==",
      "tag": "VxkFI88zrm3wj26iyBMO7g=="
    }
  }
} as const;
