name: koi-almanac

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: koi-almanac
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: pillowtalk-Qy/koi-almanac@ceb9404b4136a94e7778a6395d431bacdaa9dc7a
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/koi-almanac.svg?environment=auto&timezone=480&latitude=22.3193&longitude=114.1694
      - uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
