name: koipond

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: koipond
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: pillowtalk-Qy/koipond@fb97d7622f6d543c240db595196b17868353c59e
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/koipond-light.svg?environment=auto&timezone=480&latitude=22.3193&longitude=114.1694
            dist/koipond-dark.svg?theme=dark&environment=auto&timezone=480&latitude=22.3193&longitude=114.1694
      - uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865 # v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
